-- File generated by the BNF Converter (bnfc 2.9.6.3).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for CMM.

module CMM.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified CMM.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print CMM.Abs.Id where
  prt _ (CMM.Abs.Id i) = doc $ showString i
instance Print CMM.Abs.Program where
  prt i = \case
    CMM.Abs.PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print CMM.Abs.Def where
  prt i = \case
    CMM.Abs.DFun type_ id_ args stms -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])

instance Print [CMM.Abs.Def] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print CMM.Abs.Arg where
  prt i = \case
    CMM.Abs.ADecl type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])

instance Print [CMM.Abs.Arg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print CMM.Abs.Stm where
  prt i = \case
    CMM.Abs.SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    CMM.Abs.SDecls type_ ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 ids, doc (showString ";")])
    CMM.Abs.SInit type_ id_ exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "="), prt 0 exp, doc (showString ";")])
    CMM.Abs.SReturn exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    CMM.Abs.SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    CMM.Abs.SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    CMM.Abs.SIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])

instance Print [CMM.Abs.Stm] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print CMM.Abs.Exp where
  prt i = \case
    CMM.Abs.EBool boollit -> prPrec i 6 (concatD [prt 0 boollit])
    CMM.Abs.EInt n -> prPrec i 6 (concatD [prt 0 n])
    CMM.Abs.EDouble d -> prPrec i 6 (concatD [prt 0 d])
    CMM.Abs.EId id_ -> prPrec i 6 (concatD [prt 0 id_])
    CMM.Abs.EApp id_ exps -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exps, doc (showString ")")])
    CMM.Abs.EPost id_ incdecop -> prPrec i 6 (concatD [prt 0 id_, prt 0 incdecop])
    CMM.Abs.EPre incdecop id_ -> prPrec i 6 (concatD [prt 0 incdecop, prt 0 id_])
    CMM.Abs.EMul exp1 mulop exp2 -> prPrec i 5 (concatD [prt 5 exp1, prt 0 mulop, prt 6 exp2])
    CMM.Abs.EAdd exp1 addop exp2 -> prPrec i 4 (concatD [prt 4 exp1, prt 0 addop, prt 5 exp2])
    CMM.Abs.ECmp exp1 cmpop exp2 -> prPrec i 3 (concatD [prt 4 exp1, prt 0 cmpop, prt 4 exp2])
    CMM.Abs.EAnd exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "&&"), prt 3 exp2])
    CMM.Abs.EOr exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "||"), prt 2 exp2])
    CMM.Abs.EAss id_ exp -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 exp])

instance Print [CMM.Abs.Exp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print CMM.Abs.IncDecOp where
  prt i = \case
    CMM.Abs.OInc -> prPrec i 0 (concatD [doc (showString "++")])
    CMM.Abs.ODec -> prPrec i 0 (concatD [doc (showString "--")])

instance Print CMM.Abs.MulOp where
  prt i = \case
    CMM.Abs.OTimes -> prPrec i 0 (concatD [doc (showString "*")])
    CMM.Abs.ODiv -> prPrec i 0 (concatD [doc (showString "/")])

instance Print CMM.Abs.AddOp where
  prt i = \case
    CMM.Abs.OPlus -> prPrec i 0 (concatD [doc (showString "+")])
    CMM.Abs.OMinus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print CMM.Abs.CmpOp where
  prt i = \case
    CMM.Abs.OLt -> prPrec i 0 (concatD [doc (showString "<")])
    CMM.Abs.OGt -> prPrec i 0 (concatD [doc (showString ">")])
    CMM.Abs.OLtEq -> prPrec i 0 (concatD [doc (showString "<=")])
    CMM.Abs.OGtEq -> prPrec i 0 (concatD [doc (showString ">=")])
    CMM.Abs.OEq -> prPrec i 0 (concatD [doc (showString "==")])
    CMM.Abs.ONEq -> prPrec i 0 (concatD [doc (showString "!=")])

instance Print CMM.Abs.BoolLit where
  prt i = \case
    CMM.Abs.LTrue -> prPrec i 0 (concatD [doc (showString "true")])
    CMM.Abs.LFalse -> prPrec i 0 (concatD [doc (showString "false")])

instance Print CMM.Abs.Type where
  prt i = \case
    CMM.Abs.Type_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    CMM.Abs.Type_int -> prPrec i 0 (concatD [doc (showString "int")])
    CMM.Abs.Type_double -> prPrec i 0 (concatD [doc (showString "double")])
    CMM.Abs.Type_void -> prPrec i 0 (concatD [doc (showString "void")])

instance Print [CMM.Abs.Id] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
